"""initial migration

Revision ID: f98787a84045
Revises: 
Create Date: 2026-03-05 08:32:09.868627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f98787a84045'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('exchange_name', sa.String(length=50), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('encrypted_secret_key', sa.Text(), nullable=False),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True),
    sa.Column('encrypted_memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_exchange_name'), 'api_keys', ['exchange_name'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('used_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('used_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('user_pii',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_email', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('sync_in_progress', sa.Boolean(), nullable=False, comment='Lock flag to prevent concurrent syncs'),
    sa.Column('last_sync_end_date', sa.BigInteger(), nullable=True, comment='End date of last successful sync (UTC milliseconds)'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("(account_type = 'spot' AND product_type IS NULL) OR (account_type = 'futures' AND product_type IS NOT NULL)", name='ck_accounts_product_type_consistency'),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_api_key_id'), 'accounts', ['api_key_id'], unique=False)
    op.create_table('f_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('base', sa.String(length=20), nullable=False, comment="Base asset (e.g., 'BTC')"),
    sa.Column('quote', sa.String(length=20), nullable=False, comment="Quote asset (e.g., 'USDT')"),
    sa.Column('side', sa.String(length=10), nullable=False, comment='Trade side: long or short'),
    sa.Column('entry_date', sa.BigInteger(), nullable=False, comment='Entry timestamp in UTC milliseconds'),
    sa.Column('exit_date', sa.BigInteger(), nullable=True, comment='Exit timestamp in UTC milliseconds (null if running)'),
    sa.Column('last_update_date', sa.BigInteger(), nullable=False, comment='Last update timestamp in UTC milliseconds'),
    sa.Column('mean_entry_price', sa.Numeric(precision=36, scale=18), nullable=True, comment='Average entry price'),
    sa.Column('mean_exit_price', sa.Numeric(precision=36, scale=18), nullable=True, comment='Average exit price'),
    sa.Column('last_exit_price', sa.Numeric(precision=36, scale=18), nullable=True, comment='Last exit price (for partial closes)'),
    sa.Column('entry_size', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total entry size in base asset'),
    sa.Column('exit_size', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total exit size in base asset'),
    sa.Column('entry_usd_size', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total entry size in USD'),
    sa.Column('exit_usd_size', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total exit size in USD'),
    sa.Column('pnl', sa.Numeric(precision=36, scale=18), nullable=False, comment='Realized PnL in quote currency'),
    sa.Column('pnl_pct', sa.Numeric(precision=36, scale=18), nullable=False, comment='PnL percentage'),
    sa.Column('equity_pct_pnl', sa.Numeric(precision=36, scale=18), nullable=False, comment='PnL as percentage of account equity at trade entry'),
    sa.Column('fees', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total trading fees'),
    sa.Column('funding_fees', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total funding fees'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Trade status: running or closed'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='User rating (0-5)'),
    sa.Column('notes', sa.Text(), nullable=False, comment='User notes about the trade'),
    sa.Column('position_mode', sa.String(length=20), nullable=False, comment='Position mode: one_way or hedge_mode'),
    sa.Column('margin_mode', sa.String(length=20), nullable=False, comment='Margin mode: cross or isolated'),
    sa.Column('leverage', sa.Integer(), nullable=True, comment='Leverage multiplier'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_f_trades_account_id'), 'f_trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_f_trades_status'), 'f_trades', ['status'], unique=False)
    op.create_table('syncs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.BigInteger(), nullable=False, comment='Sync range start timestamp in UTC milliseconds'),
    sa.Column('end_date', sa.BigInteger(), nullable=False, comment='Sync range end timestamp in UTC milliseconds'),
    sa.Column('orders_recorded', sa.Integer(), nullable=False, comment='Number of orders recorded during this sync'),
    sa.Column('trades_created', sa.Integer(), nullable=False, comment='Number of trades created during this sync'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if sync failed'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='Total sync duration in milliseconds'),
    sa.Column('progress_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON data with sync progress details (pairs processed, etc.)'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syncs_account_id'), 'syncs', ['account_id'], unique=False)
    op.create_index(op.f('ix_syncs_status'), 'syncs', ['status'], unique=False)
    op.create_table('equity_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False, comment='Day start (00:00 UTC) timestamp in milliseconds'),
    sa.Column('equity', sa.Numeric(precision=36, scale=18), nullable=False, comment='Total equity (realized + unrealized) at this day'),
    sa.Column('realized_equity', sa.Numeric(precision=36, scale=18), nullable=True, comment='Equity from closed trades + transfers only (excludes unrealized)'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=36, scale=18), nullable=True, comment='Mark-to-market PnL from running trades on this day'),
    sa.Column('daily_pnl', sa.Numeric(precision=36, scale=18), nullable=True, comment='Net trading PnL change on this day'),
    sa.Column('daily_transfer', sa.Numeric(precision=36, scale=18), nullable=True, comment='Net transfer amount on this day (deposits positive, withdrawals negative)'),
    sa.Column('cumulative_net_transfer', sa.Numeric(precision=36, scale=18), nullable=True, comment='Running sum of all transfers up to this day'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uq_equity_history_account_date')
    )
    op.create_index(op.f('ix_equity_history_account_id'), 'equity_history', ['account_id'], unique=False)
    op.create_index(op.f('ix_equity_history_sync_id'), 'equity_history', ['sync_id'], unique=False)
    op.create_table('f_daily_trade_pnls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False, comment='Day timestamp at 00:00 UTC in milliseconds'),
    sa.Column('pnl', sa.Numeric(precision=36, scale=18), nullable=False, comment='Daily PnL in USD (change from previous day)'),
    sa.Column('cumulative_pnl', sa.Numeric(precision=36, scale=18), nullable=False, comment='Cumulative PnL in USD since trade start'),
    sa.Column('cumulative_pct_pnl', sa.Numeric(precision=18, scale=8), nullable=False, comment='Cumulative PnL as percentage of entry'),
    sa.Column('equity_pct_pnl', sa.Numeric(precision=18, scale=8), nullable=False, comment='PnL as percentage of account equity (placeholder for future)'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['f_trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'date', name='uq_daily_pnl_trade_date')
    )
    op.create_index(op.f('ix_f_daily_trade_pnls_trade_id'), 'f_daily_trade_pnls', ['trade_id'], unique=False)
    op.create_table('f_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('sync_id', sa.UUID(), nullable=True, comment='Sync job that imported this order'),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=False, comment='Order ID on the exchange'),
    sa.Column('base', sa.String(length=20), nullable=False, comment="Base asset (e.g., 'BTC')"),
    sa.Column('quote', sa.String(length=20), nullable=False, comment="Quote asset (e.g., 'USDT')"),
    sa.Column('side', sa.String(length=10), nullable=False, comment='Position side: long or short'),
    sa.Column('action', sa.String(length=10), nullable=False, comment='Order action: buy or sell'),
    sa.Column('open_or_close', sa.String(length=10), nullable=False, comment='Whether order opens or closes: open or close'),
    sa.Column('order_type', sa.String(length=20), nullable=False, comment='Order type: limit or market'),
    sa.Column('size', sa.Numeric(precision=36, scale=18), nullable=False, comment='Order size in base asset'),
    sa.Column('usd_size', sa.Numeric(precision=36, scale=18), nullable=False, comment='Order size in USD'),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False, comment='Execution price'),
    sa.Column('fees', sa.Numeric(precision=36, scale=18), nullable=False, comment='Order fees'),
    sa.Column('creation_date', sa.BigInteger(), nullable=False, comment='Order creation timestamp in UTC milliseconds'),
    sa.Column('execution_date', sa.BigInteger(), nullable=False, comment='Order execution timestamp in UTC milliseconds'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['f_trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_f_orders_exchange_order_id'), 'f_orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_f_orders_sync_id'), 'f_orders', ['sync_id'], unique=False)
    op.create_index(op.f('ix_f_orders_trade_id'), 'f_orders', ['trade_id'], unique=False)
    op.create_table('f_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False, comment='Transfer timestamp in UTC milliseconds'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='Transfer type: transfer_in or transfer_out'),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False, comment='Transfer amount (always positive regardless of direction)'),
    sa.Column('asset', sa.String(length=20), nullable=False, comment="Asset (e.g., 'USDT')"),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', 'type', 'amount', name='uq_f_transfers_account_date_type_amount')
    )
    op.create_index(op.f('ix_f_transfers_account_id'), 'f_transfers', ['account_id'], unique=False)
    op.create_index(op.f('ix_f_transfers_sync_id'), 'f_transfers', ['sync_id'], unique=False)
    op.create_table('sync_api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment='Exchange name (e.g., bitget, bitmart, hyperliquid)'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP method (GET or POST)'),
    sa.Column('endpoint', sa.String(length=255), nullable=False, comment='API path (e.g., /api/v2/mix/order/...)'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Query params or POST body sent'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP status code (200, 429, etc.)'),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Raw JSON response from exchange'),
    sa.Column('timestamp', sa.BigInteger(), nullable=False, comment='When the request was made (UTC ms)'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request duration in milliseconds'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['syncs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_api_logs_account_id'), 'sync_api_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_sync_api_logs_sync_id'), 'sync_api_logs', ['sync_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_api_logs_sync_id'), table_name='sync_api_logs')
    op.drop_index(op.f('ix_sync_api_logs_account_id'), table_name='sync_api_logs')
    op.drop_table('sync_api_logs')
    op.drop_index(op.f('ix_f_transfers_sync_id'), table_name='f_transfers')
    op.drop_index(op.f('ix_f_transfers_account_id'), table_name='f_transfers')
    op.drop_table('f_transfers')
    op.drop_index(op.f('ix_f_orders_trade_id'), table_name='f_orders')
    op.drop_index(op.f('ix_f_orders_sync_id'), table_name='f_orders')
    op.drop_index(op.f('ix_f_orders_exchange_order_id'), table_name='f_orders')
    op.drop_table('f_orders')
    op.drop_index(op.f('ix_f_daily_trade_pnls_trade_id'), table_name='f_daily_trade_pnls')
    op.drop_table('f_daily_trade_pnls')
    op.drop_index(op.f('ix_equity_history_sync_id'), table_name='equity_history')
    op.drop_index(op.f('ix_equity_history_account_id'), table_name='equity_history')
    op.drop_table('equity_history')
    op.drop_index(op.f('ix_syncs_status'), table_name='syncs')
    op.drop_index(op.f('ix_syncs_account_id'), table_name='syncs')
    op.drop_table('syncs')
    op.drop_index(op.f('ix_f_trades_status'), table_name='f_trades')
    op.drop_index(op.f('ix_f_trades_account_id'), table_name='f_trades')
    op.drop_table('f_trades')
    op.drop_index(op.f('ix_accounts_api_key_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('user_pii')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_exchange_name'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
